# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install coverage coveralls
  - pip install -r requirements-$TRAVIS_PYTHON_VERSION.txt

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source pds3label py.test
after_success:
  coveralls
